vlcn-io/cr-sqlite

- cfsqlite-ext.h
- cfsqlite.c
- core_init.c
Guard shared memory initialization with a mutex.
> Mutex init [3/n]

- cfsqlite-triggers.c
- notes.md
Creates the trigger responsible for merging in patches that are received from peers.
> Implement patch trigger creation [6/n]

- native/src/tableinfo.c
- native/src/tableinfo.test.c
> allow strict mode definition of primary keys

- js/examples/todomvc/src/App.tsx
- js/examples/todomvc/src/ctx.ts
- js/examples/todomvc/src/hooks.ts
- js/examples/todomvc/src/main.tsx
- js/sync-reference/client/src/DB.ts
- js/sync-reference/client/src/changeStream.ts
- js/sync-reference/client/src/index.ts
- js/sync-reference/client/src/logger.ts
- js/sync-reference/server/package.json
- js/sync-reference/server/schemas/test/test-one
- js/sync-reference/server/schemas/todo-mvc
- js/sync-reference/server/src/__tests__/db.test.ts
- js/sync-reference/server/src/changeStream.ts
- js/sync-reference/server/src/config.ts
- js/sync-reference/server/src/connection.ts
- js/sync-reference/server/src/db.ts
- pnpm-lock.yaml
and apply the schema referred to by name
> Sync server will create the requested db if it does not exist

- js/sync-reference/client/src/DB.ts
- js/sync-reference/client/src/changeStream.ts
- js/sync-reference/client/src/index.ts
note -- we can get into an infinite loop here due to incorrectly merging when nodes proxy other nodes.
See #98
> process messages received by clients

- core/src/changes-vtab-write.c
- core/src/util.c
- js/tests/nodeno-tests/package.json
- js/tests/nodeno-tests/src/__tests__/merge-check.test.ts
- pnpm-lock.yaml
Resurrecting all the property based testing that existed in the old implementation to ensure we cover all possible merge scenarios.
> use property based testing to test merge cases

- README.md
Looks like the Makefile is in `core` and not `core/src`
> Fix minor readme inaccuracy

- rs/fractindex-core/explore.sql
- rs/fractindex-core/src/fractindex.rs
- rs/fractindex-core/src/orderings.rs
- if let over unwrap
- match over tuples of options
- prefer actual size type (u8) to usize
> more idiomatic rust

- js/browser/wa-crsqlite/src/wrapper.ts
Finalize statements if the user forgets to do so.
> Auto finalize statements

- js/browser/wa-crsqlite/package.json
- js/browser/wa-crsqlite/src/wrapper.ts
- js/sync-reference/client-core/src/changeStream.ts
- pnpm-lock.yaml
- has more features
- not something I need to maintain
> switch from PromiseQueue to AsyncMutex

- .github/workflows/py-tests.yaml
- core/rs/automigrate-core/src/automigrate.rs
- core/rs/bundle/Cargo.lock
- core/rs/bundle/Cargo.toml
- core/rs/bundle/src/lib.rs
- core/rs/core/src/lib.rs
- core/rs/integration-check/tests/alter.rs
- core/rs/integration-check/tests/automigrate.rs
- core/rs/integration-check/tests/backfill.rs
- js/README.md
- js/packages/crsqlite-wasm/src/index.ts
- py/correctness/notes.md
- py/correctness/package.json
- py/correctness/tests/test_dbversion.py
- py/correctness/tests/test_schema_modification.py
- py/correctness/tests/test_sync.py
Cover schema modification and backfill
> Expand scope of python integration tests

- core/rs/automigrate-core/src/automigrate.rs
- core/rs/integration-check/tests/automigrate.rs
- core/rs/integration-check/tests/backfill.rs
- core/rs/integration-check/tests/pk_only_tables.rs
- core/rs/integration-check/tests/teardown.rs
- core/rs/integration-utils/Cargo.lock
- core/rs/integration-utils/Cargo.toml
- core/rs/integration-utils/src/lib.rs
We need this so all memory is released and we can invoke `rust valgrind`
> hack to allow tearing down of sqlite after all rust tests are run

- js/packages/client-server-common/src/__tests__/index.test.ts
- js/packages/client-server-common/src/index.ts
lengths wouldn't ever be negative.
> Use unsigned in for lengths

- js/packages/browser-tests/package.json
- js/packages/client-core/package.json
- js/packages/client-server-common/package.json
- js/packages/client-websocket/package.json
- js/packages/create-web/package.json
- js/packages/crsqlite-wasm/package.json
- js/packages/node-allinone/package.json
- js/packages/node-tests/package.json
- js/packages/p2p/package.json
- js/packages/react/package.json
- js/packages/rx-query/package.json
- js/packages/rx-tbl/package.json
- js/packages/sandbox-node/package.json
- js/packages/sandbox/package.json
- js/packages/server-core/package.json
- js/packages/server-websocket/package.json
- js/packages/xplat-api/package.json
- js/packages/xplat-tests/package.json
- js/tsbuild-all/package.json
- package.json
- pnpm-lock.yaml
- typescript 5
- vite 4
- vitest 0.30
> Upgrade package dependencies

- core/src/triggers.c
- js/packages/node-tests/package.json
- js/packages/node-tests/src/__tests__/fract-check.test.ts
- js/packages/node-tests/src/__tests__/user-reports.test.ts
- pnpm-lock.yaml
Why would https://github.com/vlcn-io/cr-sqlite/blob/main/py/correctness/tests/test_sync_prop.py never have caught this? 🤔
> Fix incorrect handling of `NULL` values on merge

- core/rs/core/src/backfill.rs
- core/src/sqlite/shell.c
- core/src/sqlite/sqlite3.h
- core/src/sqlite/sqlite3ext.h
see #247 
Left joins were doing index scans rather than searches. Using a sub-query does the right thing, however. The results are equivalent, not sure why the query plans are so different 🤷‍♂️
> Backfill efficiency

- .changeset/mighty-goats-sell.md
- .changeset/pre.json
- .changeset/proud-moles-peel.md
- .changeset/silver-beds-train.md
- js/packages/direct-connect-nodejs/CHANGELOG.md
- js/packages/direct-connect-nodejs/package.json
- js/packages/direct-connect-nodejs/src/config/DefaultConfig.ts
- js/packages/direct-connect-nodejs/src/config/TestConfig.ts
- js/packages/direct-connect-nodejs/src/private/FSNotify.ts
- js/packages/direct-connect-nodejs/src/private/__tests__/FSNotify.test.ts
- js/packages/direct-connect-nodejs/src/private/touchHack.ts
- js/packages/direct-connect-nodejs/src/private/util.ts
- js/packages/sandbox/CHANGELOG.md
- js/packages/sandbox/package.json
some attempts at fixing file watching on windows
> fixes to watch db changes on windows

- core/rs/core/src/bootstrap.rs
- core/rs/core/src/consts.rs
- core/rs/core/src/lib.rs
- core/src/crsqlite.c
- core/src/crsqlite.h
- core/src/crsqlite.test.c
- core/src/rust.h
This is not quite all of it yet.
As we move more we can start to get rid of `extern "C"`
> move some extension bootstraping logic to Rust

- core/rs/core/src/changes_vtab.rs
- core/rs/core/src/changes_vtab_write.rs
- core/rs/core/src/lib.rs
- core/rs/core/src/pack_columns.rs
- core/src/changes-vtab-write.c
still rather ugly "rust written as if it were c" but we can't get very idiomatic until more callers and dependencies are migrated.
> convert did_cid_win to rust

- core/rs/core/src/bootstrap.rs
- core/src/crsqlite.c
- core/src/rust.h
> alert when the user is opening an unsupported db due to cr-sqlite upgrade

- core/rs/core/src/bootstrap.rs
Useful when making a backup and then restoring.
> ensure a site id is present on init

- .github/workflows/publish.yaml
- core/Makefile
To run locally:
```
cargo install cargo-ndk
export ANDROID_NDK_HOME=/path/to/NDK
export ANDROID_TARGET=aarch64-linux-android
cd core
make loadable
```
> actually set the android target 🤦‍♂️

- core/rs/core/src/automigrate.rs
If the schema being migrated to has syntax errors we need to report that.
We also should not panic if it has syntax errors which is the case when an extension is statically linked and requires cleanup.
> better error messaging when automigration fails

- core/rs/integration_check/src/t/tableinfo.rs
we were creating a pointer to nothing in the tests 😮
> fix err_msg pointer creation in tests

- core/rs/core/src/backfill.rs
- py/correctness/test.sh
- py/correctness/tests/test_commit_alter_perf.py
> use an `except` query for finding new rows during backfill
