vlcn-io/cr-sqlite

cfsqlite.c
The db version global always points to the next db version.
This means that all triggers can use the current value for their writes and on transaction commit, we'll bump the cached db version in preparation for the next write.
dbversion is an atomic int and threadsafe.
test plan:
```
sqlite> select cfsql_dbversion();
-9223372036854775806
sqlite> create table foo (a);
sqlite> select cfsql_dbversion();
-9223372036854775805
sqlite> insert into foo values (1);
sqlite> select cfsql_dbversion();
-9223372036854775804
```
=> Commit hook to bump db version on write [4/n]

cfsqlite-triggers.c, cfsqlite-triggers.h, cfsqlite-triggers.test.c, cfsqlite.c, notes.md
The code isn't so important -- mainly the idea needs review.
This gives each row that is touched a unique version which allows us to chunk the replication process.
If a bunch of rows have the same version we would need to ensure all of those rows are sent and applied
before moving to the next set of rows.
This is because peers keep track of what updates they have from other peers via peer version numbers.
If peer A sends version 10, skipping version 0-9, to peer B then peer B will never ask A for anything prior to 10.
I'm also skeptical that tagging all rows that are in a transaction with the same version actually accomplishes anything.
The idea behind tagging rows that are in the same transaction with the same version was to be able to try to maintain transaction gurantees.
While it …
=> [needs-review] bump db version in triggers rather than commit hook

README.md
Hi there!
I just noted what I think is a minor typo in the README. `LWWW` should probably be `LWW` (unless it's a different conflict strategy).
Awesome work on this project btw; I'm really excited to watch it progress :)
=> Fix LWWW -> LWW typo

js/rx/table-based/src/index.ts, js/wasm-esm/wa-crsqlite/src/wrapper.ts
https://user-images.githubusercontent.com/1009003/203170976-285bfead-72c1-4295-b068-62eadf6da251.mov
=> keep tabs in sync via broadcast channel

js/examples/p2p-todomvc/src/main.tsx, js/replicators/whole-db/src/WholeDbReplicator.ts, native/src/changes-vtab-write.c, native/src/changes-vtab.c, notes.md, py/correctness/tests/test_sync.py
1. We weren't moving our logical clock forward on merge of a winner
2. We didn't return the logical clock value of deletes
3+ way merge works fine now --
https://user-images.githubusercontent.com/1009003/204034968-54d8b9c5-b3b3-4c48-b2ac-27e0b83843e1.mov
Need to resurrect unit and integration tests for multi way merges --
https://github.com/vlcn-io/cr-sqlite/blob/orig-approach/prototype/replicator/src/__tests__/merge-random-1.test.ts
https://github.com/vlcn-io/cr-sqlite/blob/orig-approach/prototype/replicator/src/__tests__/merge-random-2.test.ts
that we never ported over when we re-wrote the implementation from TypeScript to C.
=> Fix multi way merge bug 🤦‍♂️

native/src/changes-vtab-read.c, native/src/tableinfo.c, native/src/triggers.c, native/src/util.c
I didn't manage to get `make` running on my Windows setup. So, compiled everything manually with `cl` using the following commands:
**loadable**:
```bash
cl /I src/ /I src/sqlite /O2 /LD /DSQLITE_PATH_DATE="\"2022-12-04T18:57:31Z+0700\"" /DSQLITE_PATH_VERSION="\"v0.1.0\"" /DSQLITE_PATH_SOURCE="\"eaffe9f47859b6bf6926912d5006d64a1be94896\"" src/crsqlite.c src/util.c src/tableinfo.c src/triggers.c src/changes-vtab.c src/changes-vtab-read.c src/changes-vtab-common.c src/changes-vtab-write.c src/ext-data.c src/get-table.c /link /OUT:dist/crsqlite.dll
```
**sqlite3**:
```bash
cl /DSQLITE_PATH_DATE="\"2022-12-04T19:56:46Z+0700\"" /DSQLITE_PATH_VERSION="\"v0.1.0\"" /DSQLITE_PATH_SOURCE="\"208b529213d5c9a447ef8693683596a6fc134016\"" /DSQLITE_THREADSAFE=0 /DSQLITE_OMIT_LOAD_EXTENSION=1 …
```
=> Fix Windows build by rewriting c99 specific code

native/Makefile
Just a small change to fix the vanilla target in `native/Makefile`
=> fix source path for native vanilla build

.github/workflows/c-valgrind.yaml, native/src/tests.c
Registering the extension via `sqlite3_auto_extension()` allocates a buffer for the list of extensions loaded.
This buffer has to be freed via `sqlite3_reset_auto_extension()` which is also called from `sqlite3_shutdown()` and potentially can clean up other resources.
This pr adds a call to `sqlite3_shutdown()` at the end of the test suite to mitigate the valgrind warning.
=> Fix valgrind reachable memory error

js/sync-reference/client/src/DB.ts, js/sync-reference/server/src/db.ts, native/src/changes-vtab-write.c, native/src/changes-vtab-write.h, native/src/crsqlite.test.c
fixes #98
Tie braking on value allows the server to mask the site ids of clients.
This is important for privacy / to prevent clients from discovering one another.
This masking also allows us to ensure a client never sends changes it received from a server back to the server, thus starting a loop.
https://user-images.githubusercontent.com/1009003/206575697-90160393-1db7-4ff8-a576-ec3807a65477.mov
=> tie break on value rather than site id

core/Makefile, core/src/changes-vtab.c, core/src/changes-vtab.h, core/src/crsqlite.c, core/src/ext-data.c, core/src/ext-data.h, core/src/seen-peers.c, core/src/seen-peers.h, core/src/seen-peers.test.c, core/src/tableinfo.c, core/src/tests.c, core/src/triggers.c
This updates `crsql_changes` to record the clocks of peers seen during the insert.
Automatically tracking peer clocks + creating a table to track clocks makes the authoring of networking layers simpler. The authors don't need to track peer clocks on their own.
As an optimization, however, they may still wish to track clocks internally. That optimization would be to enable streaming of changes before having those changes acknowledge and committed by peers.
=> Record peer clocks on insert into `crsql_changes`

js/browser/crsqlite-wasm/CHANGELOG.md, js/browser/crsqlite-wasm/package.json, js/examples/basic-browser-setup/CHANGELOG.md, js/examples/basic-browser-setup/package.json, js/rx-tbl/package.json
Currently an unsafe fix for Safari. It rests on the unvalidated assumption that Safari is wrapping entries in the function table which breaks reference equality.
We need to validate that the underlying functions are indeed the expected functions
https://sqlite.org/forum/forumpost/07ba8ac75e
=> Safari bug

core/Makefile, core/binding.gyp, core/package.json, core/src/changes-vtab-write.c, core/src/changes-vtab.c, core/src/changes-vtab.h, core/src/seen-peers.c, core/src/seen-peers.h, core/src/seen-peers.test.c
Simplifies writing of networking layers.
See latest docs -- https://vlcn.io/docs/guide-sync#using-tracked-peers
=> track max clock values we see for peers on insert to `crsql_changes`

.github/workflows/rs-valgrind.yml, .gitmodules, core/rs/automigrate-core/src/automigrate.rs, core/rs/integration-check/tests/automigrate.rs, core/rs/integration-check/tests/backfill.rs, core/rs/integration-check/tests/pk_only_tables.rs, core/rs/integration-check/tests/teardown.rs, core/rs/integration-utils/src/lib.rs
given rust is not immune to memory leaks -- esp when interfacing with C.
Case and point, this leak which was uncovered: https://github.com/vlcn-io/cr-sqlite/pull/171/commits/26b01512869426d773c0cf4503075b7dbd183aa1
> calling closedb gave ownership of the DB to closedb. Closedb would then try dropping the DB on return.
> Statements were not yet finalized so this drop attempt would fail and not reclaim memory.
=> Run valgrind against Rust integration tests

js/packages/p2p/src/WholeDbReplicator.ts
When I was playing around with the p2p package, eslint told me there were a few [floating promises](https://typescript-eslint.io/rules/no-floating-promises/). This PR fixes two that don't cause externally visible changes, but there are a few others that would involve function signature changes, namely [in the dispose](https://github.com/vlcn-io/cr-sqlite/blob/main/js/packages/p2p/src/WholeDbReplicator.ts#L133), [newConnection](https://github.com/vlcn-io/cr-sqlite/blob/main/js/packages/p2p/src/WholeDbReplicator.ts#L224), and in [schemaChanged](https://github.com/vlcn-io/cr-sqlite/blob/main/js/packages/p2p/src/WholeDbRtc.ts#L74). I'm not nearly experienced enough in JavaScript (or websockets) to know if changing those (or even this PR) is a good idea.
=> Less floating promises

README.md, core/README.md, core/src/changes-vtab-read.c, core/src/changes-vtab-read.h, core/src/changes-vtab-read.test.c, core/src/changes-vtab.c, core/src/changes-vtab.h, core/src/changes-vtab.test.c, core/src/crsqlite.test.c, js/packages/node-tests/src/__tests__/xplat.test.ts, js/packages/node-tests/src/fill.ts, js/packages/p2p/src/WholeDbReplicator.ts, js/packages/server-core/src/db.ts, js/packages/xplat-tests/src/index.ts, py/correctness/tests/test_sync.py
Note that `pk` and `tbl_name` filters against `crsql_changes` are not yet performant and require table scans.
db_version is indexed and performant. tbl_name and pk are indexed as well and could be made performant with some tweaks to how the virtual table passes information to the base tables.
=> Support all the expected filters against `crsql_changes`

core/src/changes-vtab-write.c, core/src/changes-vtab.c, core/src/crsqlite.c, core/src/ext-data.c, core/src/ext-data.h, core/src/rows-impacted.test.c, core/src/tests.c, notes.md, py/perf/notes.md
This allows users to know whether or not an insert into `crsql_changes` actually made any modifications.
```sql
BEGIN;
INSERT INTO crsql_changes VALUES ...;
SELECT crsql_rows_impacted();
COMMIT;
```
`crsql_rows_impacted` will return the total number of rows modified by all inserts into `crsql_changes` in the current transaction. On transaction commit, the value is reset to 0.
- Each connection has its own copy of this counter so concurrent transactions are isolated since connections can't be shared between threads (a SQLite constraint).
- This count is accumulated at the _top level transaction_. In other words, you cannot get independent counts for nested transactions / savepoints.
=> implement crsql_rows_impacted 

README.md, core/README.md, core/rs/core/src/automigrate.rs, core/rs/core/src/backfill.rs, core/rs/core/src/lib.rs, core/rs/core/src/util.rs, core/src/crsqlite.c, core/src/crsqlite.h, core/src/crsqlite.test.c, core/src/ext-data.c, core/src/tableinfo.h, core/src/util.c, core/src/util.test.c, py/correctness/notes.md, py/correctness/tests/test_schema_modification.py, py/correctness/tests/test_sync.py
- do not backfill metadata for default values in a migration
- default values, that are not explicitly set by an update/insert, always lose in a tie
- handle when primary key memberships is changed during a migration
- handle when rows are removed in a migration
- handle when rows are added in a migration
- support two notions of migration process:
- schema migration: does not move db version forward. This is any operation done between begin and commit alter.
- data migration: data modifications after commit_alter. These operation will move db_version for the new writes. Moving these operations before commit_alter will not move the db version.
Doing data migrations in the schema migration phase is useful when you know that a migration will leave nodes in a consistent state and not require …
=> Many more schema migration tests + bug fixes

core/src/changes-vtab-read.c, core/src/changes-vtab-read.h, core/src/changes-vtab-read.test.c, core/src/changes-vtab-rowid.test.c, core/src/changes-vtab-write.c, core/src/changes-vtab.c, core/src/changes-vtab.h, core/src/tableinfo.c, core/src/tableinfo.h, core/src/tableinfo.test.c, core/src/tests.c
Previously we did not return unique rowids for each row returned by crsql_changes. Now we do.
Note that _rowid_ is not stable as it is derived from sqlite _rowid_'s which are not stable.
> If the [rowid](https://www.sqlite.org/lang_createtable.html#rowid) is not aliased by [INTEGER PRIMARY KEY](https://www.sqlite.org/lang_createtable.html#rowid) then it is not persistent and might change. In particular the [VACUUM](https://www.sqlite.org/lang_vacuum.html) command will change rowids for tables that do not declare an INTEGER PRIMARY KEY. Therefore, applications should not normally access the rowid directly, but instead use an INTEGER PRIMARY KEY.
https://www.sqlite.org/rowidtable.html
but it will be stable between vacuums.
=> implement rowid properly for crsql_changes

js/packages/react/src/queryHooks.ts, scripts/update-pkgjson.sh
This is an optimization for React to reduce re-renders when data did not change.
In the future, callbacks and queries will not even be made if the data didn't change. To be implemented in the LiveSQL layer.
=> keep referential equality if returned data from db did not change

core/rs/core/src/automigrate.rs, core/rs/core/src/lib.rs, core/rs/integration-check/tests/automigrate.rs, js/build-wasm-dbg.sh, js/packages/browser-tests/cypress/component/automigrate.cy.ts, js/packages/crsqlite-wasm/src/DB.ts, js/packages/node-tests/src/__tests__/automigrate.test.ts
If the extension is statically linked then the in-memory DB that is opened to facilitate auto-migrations will have the extension loaded.
When this is the case, we must do extra cleanup of the in-memory DB.
This PR exposes a second arg to `crsql_automigrate` which allows the user to pass custom cleanup logic.
=> Fix `crsql_automigrate` for cases where the `crsql` extension has been statically linked

core/src/crsqlite.c
Existing DBs wouldn't get their crsqlite version recorded if they were updated to a new version of crsqlite.
=> correctly records crsqlite version in the db after an upgrade of that db

core/Makefile
this'll allow us to explore whether or not a byte code representation of the query is enough for our reactivity layer or if we need to pull in a query parser
https://fly.io/blog/sqlite-virtual-machine/
=> compile in the bytecode extension to the sqlite cli

core/src/changes-vtab-write.c, core/src/rows-impacted.test.c
`__crsql_del` row insertions into `crsql_changes` didn't count towards `crsql_rows_impacted`.
So, I'm not sure if that's the right spot, but it appears to be working as intended.
The early return from the modified function prevented the counter from being incremented. I also added it to the `isPkOnly` branch, even though I'm not sure when that gets triggered.
=> Count deletes towards rows impacted

core/src/changes-vtab-read.c, core/src/changes-vtab-read.test.c, core/src/changes-vtab.c, core/src/rows-impacted.test.c, py/correctness/test.sh, py/correctness/tests/test_crsql_changes_filters.py, py/correctness/tests/test_sync_prop.py
While working with the `crsql_changes` table, I noticed some queries didn't work at all and others were very slow. I'm working with a test table of 1800000 rows, and there are over 3 million crsql_changes row.
I'm using this query in my testing:
```sql
SELECT DISTINCT(db_version) FROM crsql_changes WHERE site_id IS ? AND db_version > ? AND db_version < ?
```
Initial execution time for this query: **8s**
Using `EXPLAIN QUERY PLAN` helped me figure out that no indexes were being used.
This should fix #245 by ignoring "unusable" constraints in `xBestIndex`. According to the docs:
> The `aConstraint[]` array contains information about all constraints that apply to the virtual table. But some of the constraints might not be usable because of the way tables are ordered in a join. The …
=> Query performance improvements (xBestIndex fix + no default ordering)

.github/workflows/publish.yaml
For cases where we are cross-compiling we need to install the target for the current toolchain manually.
Is there not a way to tell Rust to use the same toolchain for all targets in the https://github.com/vlcn-io/cr-sqlite/blob/main/core/rs/core/rust-toolchain.toml file?
=> Fix the build for arm releases

core/rs/bundle/Cargo.lock, core/rs/core/Cargo.lock, core/rs/core/Cargo.toml, core/rs/core/src/concat_columns.rs, core/rs/core/src/lib.rs, core/rs/integration-check/Cargo.lock, core/rs/integration-check/Cargo.toml, core/rs/integration-check/tests/concat_columns.rs
Format:
```
[num_columns:u8,...[(type(0-3),num_bytes?(3-7)):u8, length?:i32, ...bytes:u8[]]]
```
The byte used for column type also encodes the number of bytes used for the integer.
e.g.: `(type(0-3),num_bytes?(3-7)):u8`
first 3 bits are type
last 5 encode how long the following integer, if there is a following integer, is. 1, 2, 3, ... 8 bytes.
Not packing an integer into the minimal number of bytes required is rather wasteful.
E.g., the number `0` would take 8 bytes rather than 1 byte.
---
We'll use this in three places:
1. In `select` statements, replacing `quote() || ...` with `crsql_concat_columns(...)`
2. In the vtab write path.
3. In the vtab `next` path.
For (2), we'll create a function in Rust that:
1. Takes an enum indicating statement type
2. Takes a pointer to a sqlite_stmt
4. …
=> Binary format for encoding many columns into a single column

core/Makefile, core/src/ext-data.c, core/src/ext-data.h, core/src/stmt-cache.c, core/src/stmt-cache.h, core/src/stmt-cache.test.c, core/src/tests.c, core/src/uthash.h, core/src/util.c, notes.md
A cached statement must never have more than one outstanding reference. It is an error to get two references to the same cached statement and attempt to use them concurrently.
---
Doing this in C as passing BTreeMap and ExtData over FFI is a bit more than I'm ready for.
If we did the cache in Rust:
- pExtData must retain a pointer to a Rust created Map
- Ownership of this pointer leaves Rust and goes to C
- Rust needs bindings for pExtData so it can read its map out and save its map to it
=> prepared statement cache

core/Makefile, notes.md
so I thought this would be really hard and have been avoiding it for months.
Turns out we just needed to:
1. set the target triple
2. build rust's std from source
3. set the sysroot to the iPhoneOS.sdk
To use:
```
cr-sqlite> cd core
cr-sqlite/core> export BUILD_FOR_IOS=true; make loadable
```
**edit (latest revision):** 
```
cr-sqlite> cd core
cr-sqlite/core> export IOS_TARGET=aarch64-apple-ios; make loadable
```
Now in `dist` you'll have a `crsqlite.dylib` for `ios`
```
ls -ltrh dist
total 37992
-rw-r--r--  1 tantaman  staff   8.3M Jul  7 21:52 sqlite3-extra.c
-rw-r--r--  1 tantaman  staff   5.1M Jul 10 10:59 libcrsql_bundle-loadable.a
-rwxr-xr-x  1 tantaman  staff   848K Jul 10 10:59 crsqlite.dylib
```
This assumes that we can load `dylib` extensions into `sqlite` on iOS. @alanjhughes …
=> update makefile to support ios builds

core/rs/core/src/lib.rs, core/rs/core/src/unpack_columns_vtab.rs, core/rs/integration-check/tests/pack_columns.rs
```sql
sqlite> create table foo (a, b, c);
sqlite> insert into foo values (1,2,3);
sqlite> select cell from crsql_unpack_columns where package = (select crsql_pack_columns(a,b,c) from foo);
1
2
3
```
The virtual table rust bindings are rather low level at the moment. Need to use them a bit more to understand the best ergonomics that also minimize copying across the ffi boudnary.
=> table valued function to unpack columns

js/packages/direct-connect-nodejs/src/private/DB.ts
better-sqlite3 is garbage at handling bigints. It truncates integers without warning if they are > 2^53. You can change the behavior to treat all integers as bigints but this is problematic too since not all ints are bigints.
Anyway... enable this behavior for the `changes` statements where all numbers can be 2^64.
=> safe bigints for better-sqlite3 changeset pulling

core/rs/core/src/alter.rs, core/rs/core/src/backfill.rs, core/rs/core/src/c.rs, core/rs/core/src/changes_vtab_write.rs, core/rs/core/src/lib.rs, core/rs/core/src/teardown.rs, core/rs/core/src/triggers.rs, core/rs/core/src/util.rs, core/rs/integration-check/tests/backfill.rs, core/src/changes-vtab-read.test.c, core/src/changes-vtab-rowid.test.c, core/src/changes-vtab.test.c, core/src/consts.h, core/src/crsqlite.c, core/src/crsqlite.test.c, js/packages/node-tests/src/__tests__/user-reports.test.ts, py/correctness/test.sh, py/correctness/tests/test_insert_new_rows.py, py/correctness/tests/test_sandbox.py, py/correctness/tests/test_schema_modification.py, py/correctness/tests/test_seq.py, py/correctness/tests/test_sync.py
Rather than moving 100% to a model that can support re-insertions immediately, I decided to break the work up into chunks.
Re-insertion requires us to keep a metadata at the row level on initial row creation. This diff adds that. (note: I'm a bit concerned about metadata growth so a follow on improvement would be to restructure our metadata format so it is smaller: #293. Looks like we can compress by 5x in average case!).
A nice side-effect is that this diff also solved all the primary key modification issues ( #50). I.e., when doing an `UPDATE` to change a primary key from one value to another, this is actually a `DELETE` of the row with the old primary key and `INSERT` of the row with the new one since a primary key is the identity of a row.
Follow on diffs would be to:
- Keep …
=> Always mark a sentinel on row create, record delete on pk modification, record create on pk modification

core/rs/core/src/alter.rs, core/rs/core/src/c.rs, core/rs/core/src/changes_vtab_write.rs, core/rs/core/src/triggers.rs, core/rs/integration-check/tests/backfill.rs, core/rs/integration-check/tests/pk_only_tables.rs, core/src/crsqlite.test.c, core/src/rows-impacted.test.c, js/packages/node-tests/src/__tests__/user-reports.test.ts, py/correctness/test.sh, py/correctness/tests/test_insert_new_rows.py, py/correctness/tests/test_schema_modification.py, py/correctness/tests/test_seq.py, py/correctness/tests/test_sync.py
A follow up to #292 and the next step in supporting re-insertion.
Re-insertion needs to track causal length in a single metadata entry for the row. This collapses delete and create metadata to a single row but still uses delete-wins semantics.
Next PR will switch to causal length semantics.
=> use a single sentinel column to represent delete and create

core/rs/core/src/triggers.rs, py/correctness/test.sh, py/correctness/tests/test_cl_triggers.py
We need to test all the various cases to ensure:
1. Deletes result in even CL
2. Inserts result in odd CL
3. Updates do not change CL
edge cases:
- upserts to update existing rows in base tables
- modifying primary key columns to cause deletes and creations of new rows in an update
- trying to delete the same row again?
- trying to insert the same row again?
- updates to existing row(s)
for #71
=> start bumping causal length in triggers

core/rs/core/src/c.rs, core/rs/core/src/changes_vtab_write.rs, core/src/ext-data.c, core/src/ext-data.h, py/correctness/tests/test_site_id_lookaside.py
need to implement the new test in py/correctness/tests/test_site_id_lookaside.py
=> fix ordinal mapping -- don't re-insert if it is present!

.github/workflows/publish.yaml, core/Makefile
You can reproduce this build locally via:
```
cd core
export ANDROID_NDK_HOME=/path/to/your/ndk
export ANDROID_TARGET=aarch64-linux-anrdoid; make
```
The NDK can be downloaded from here: https://developer.android.com/ndk/downloads
This build works by:
1. Swapping out `clang` with the NDK version of clang: `CC = $(NDK)/toolchains/llvm/prebuilt/$(NDK_HOSTARCH)/bin/clang`
2. Setting the `sysroot`: `--sysroot=$(NDK)/toolchains/llvm/prebuilt/$(NDK_HOSTARCH)/sysroot`
Looks like the NDK paths are dependent on the host architecture
`NDK_HOSTARCH = linux-x86_64` (https://github.com/vlcn-io/cr-sqlite/pull/327/files#diff-d486e601a844f08eaa052d963bedbdd8a7db76d664a5f44fe34bf4fd6db1064aR46-R47)
so to reproduce the build locally you'll need to set your host architecture to the correct one for your …
=> Android build

core/rs/fractindex-core/src/as_ordered.rs, py/correctness/tests/test_as_ordered.py
`crsql_as_ordered` would fail if the table schema specified a type for the column used to order by.
E.g.,
```sql
CREATE TABLE test (id, spot TEXT, list TEXT);
```
Assigning `TEXT` to `spot` would cause inserts to spot to be treated as text. This meant out `-1` and `1` shorthand for pre-pend and append would fail to compare and write an invalid fractional index. Fix that by casting the `ordering` column before using it.
=> Fix a bug in the fractional indexing implementation when a column type is specified

core/rs/fractindex-core/src/fractindex.rs, core/src/rs-fract.test.c, py/correctness/tests/test_as_ordered.py
Closes https://github.com/vlcn-io/cr-sqlite/issues/179.
Fractional indexing now uses base 95 for more efficiency. All the tests were updated accordingly.
=> Migrate to base 95 fractional indexing

core/src/rust.h
I typoed this when porting to Rust. Should be `sqlite_int64` in `rust.h` not `int`
This typo fatals the WASM builds
=> fix db version signature

.github/workflows/publish.yaml
=> zip loadable extensions so people do not need to rename them

README.md, core/rs/bundle_static/Cargo.lock, core/rs/core/src/bootstrap.rs, core/rs/core/src/tableinfo.rs, core/rs/integration_check/Cargo.lock, core/src/changes-vtab.c, core/src/changes-vtab.test.c, core/src/crsqlite.test.c, py/correctness/src/crsql_correctness/__init__.py, py/correctness/test.sh, py/correctness/tests/test_cl_merging.py, py/correctness/tests/test_insert_new_rows.py, py/correctness/tests/test_schema_modification.py, py/correctness/tests/test_site_id_lookaside.py, py/correctness/tests/test_siteid.py, py/correctness/tests/test_sync.py
1. We compact out side ids so there isn't much advantage to making it null for local writes anymore
2. This cleans up the interface so users don't have to do weird coalescing
3. This allows us to make https://github.com/vlcn-io/cr-sqlite/pull/386 a reality by switching tie breaks to site_ids
=> Make site_id required

core/rs/core/src/changes_vtab_write.rs, core/src/crsqlite.test.c, core/src/rows-impacted.test.c, py/correctness/test.sh, py/correctness/tests/test_cl_merging.py, py/correctness/tests/test_sync.py
This is to allow us to preserve transactionality of mutations.
In conjunction with #386, this'll allow fields to be all set together or all reverted together.
E.g., a case where `x` & `y` coordinates are supposed to be updated together or not at all.
=> switch tie-breaker to site_id

core/Makefile, core/rs/bundle/Cargo.toml, core/rs/bundle_static/Cargo.toml, core/rs/core/Cargo.toml, core/rs/core/src/backfill.rs, core/rs/core/src/changes_vtab_write.rs, core/rs/core/src/create_cl_set_vtab.rs, core/rs/core/src/unpack_columns_vtab.rs, core/rs/integration_check/Cargo.toml, core/src/changes-vtab.c, core/src/crsqlite.c, libsql-sync.sh
Syncing to libsql is a bit tedious. Add some `ifdefs` and `#[cfg(feature = "libsql")]` so no manual modifications are required after sync.
=> libsql ifdefs

core/rs/core/src/tableinfo.rs, py/correctness/test.sh, py/correctness/tests/test_cl_merging.py
This ensures that if two fields should always change together that they always will as when one loses a merge the other one will also lose the merge.
Hmm, except in the case where the clocks are equal and then we tie break on value. Would be better to tie break on peer id for consistency.
=> use db_version for col_version

core/rs/core/src/tableinfo.rs, py/correctness/tests/test_cl_merging.py
=> Revert "use db_version for col_version"

core/rs/core/src/changes_vtab_write.rs, core/src/crsqlite.test.c, core/src/rows-impacted.test.c, py/correctness/tests/test_cl_merging.py, py/correctness/tests/test_sync.py
Why?
- This has been the behavior for over a year
- We have production deployments that we shouldn't break
- We can re-introduce site_id tie breaking as a configuration option if anyone ever needs it
- We are no longer doing `col_version = db_version` for reasons documented in https://github.com/vlcn-io/cr-sqlite/pull/405, removing the need for this change
=> revert #393

core/Makefile, core/nodejs-install-helper.js, core/rs/core/src/consts.rs, core/rs/core/src/lib.rs, core/rs/core/src/sha.rs
```
rlwrap ./dist/sqlite3
SQLite version 3.42.0 2023-05-16 12:36:15
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> select crsql_sha();
53c08576a4b3c27a2423ff2b4143cdd38ff402f5
sqlite>
```
=> Fix version & add a function to report the commit sha used to create the binary

core/rs/bundle/Cargo.lock, core/rs/core/Cargo.lock, core/rs/core/src/c.rs, core/rs/core/src/changes_vtab_write.rs, core/rs/core/src/config.rs, core/rs/core/src/lib.rs, core/rs/core/src/sha.rs, core/rs/fractindex-core/Cargo.lock, core/src/ext-data.c, core/src/ext-data.h, py/correctness/src/crsql_correctness.egg-info/SOURCES.txt, py/correctness/tests/test_config.py, py/correctness/tests/test_sync.py
Adds 2 functions `crsql_config_set(name, value)` and `crsql_config_get(name)`. They enable setting and getting config settings persisted to the database, but also available in `crsql_ExtData`.
The first and only setting right now is `merge-equal-values` making sure there's always a winner by tie-breaking on `site_id` when everything else is equal.
=> Add option to compare site_id when values are equal to determine ultimate winner

core/rs/core/src/lib.rs
So we were having some issues in release builds, apparently there is an undefined behavior conversion from "main" (rust string, NOT NULL TERMINATED) to &str using `CStr::from_ptr` (which expects a null terminated string)
This seems to be a decent fix, although you might want to go over similar code, there might be cases I missed.
Also the error codes are slightly vague, since all these conversions just return "out of memory" even though it's not what's going on.
Thanks.
=> Fix missing null terminator in schema name

core/nodejs-install-helper.js
`import something from "somewhere" assert { type: "json" };` has been deprecated in favour of `import something from "somewhere" with { type: "json" };`. Therefore on the latest node versions (tested on `22.2.0` and `22.3.0`) the library just doesn't install:
```
import pkg from "./package.json" assert { type: "json" };
^^^^^^
SyntaxError: Unexpected identifier 'assert'
at compileSourceTextModule (node:internal/modules/esm/utils:337:16)
at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:164:18)
at callTranslator (node:internal/modules/esm/loader:429:14)
at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:435:30)
at async ModuleJob._link (node:internal/modules/esm/module_job:106:19)
Node.js v22.3.0
```
This is a simple fix that changes `assert` to `with` in …
=> fix deprecated import assertion
